name: test ci

env:
  PYTHONPATH: ${{ github.workspace }}/test

on:
  push:
    branches: [ main, dev, 'feature/**' ]
  pull_request:
    branches: [ main, dev ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Run tests
        run: python -m unittest discover -s tests

  deploy-main-dev:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Run server
        run: python main.py

  deploy-feature:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/feature/'

    steps:
      - name: Success
        run: echo 'success'